In [1]:
import numpy as np

In [3]:
a = [[11, 12, 13], [21, 22, 23], [31, 32, 33]]
print(a)

[[11, 12, 13], [21, 22, 23], [31, 32, 33]]


In [8]:
A = np.array(a)
print(A)

[[11 12 13]
 [21 22 23]
 [31 32 33]]


In [10]:
np.ndim(A)

2

In [11]:
A.ndim

2

In [12]:
A.shape

(3, 3)

In [13]:
A.size

9

In [14]:
A[1][2]

23

In [15]:
B = A + 10

In [16]:
print(B)

[[21 22 23]
 [31 32 33]
 [41 42 43]]


In [17]:
A + B 

array([[32, 34, 36],
       [52, 54, 56],
       [72, 74, 76]])

In [18]:
# Matrix multiplication
np.dot(A, B)

array([[1136, 1172, 1208],
       [2066, 2132, 2198],
       [2996, 3092, 3188]])