# Introduction to Elastic Net with Python

$Description:$...

## Examples

Source: https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.ElasticNet.html

#### Libraries

In [68]:
from sklearn.linear_model import ElasticNet, ElasticNetCV
from sklearn.datasets import make_regression
import numpy as np

#### Modelling: Elastic Net

In [90]:
X, y = make_regression(n_features=2, random_state=0)
regr = ElasticNet(random_state=0)
regr.fit(X, y)

ElasticNet(alpha=1.0, copy_X=True, fit_intercept=True, l1_ratio=0.5,
           max_iter=1000, normalize=False, positive=False, precompute=False,
           random_state=0, selection='cyclic', tol=0.0001, warm_start=False)

#### Results

In [53]:
print("Regression coefficients:", regr.coef_)

Regression coefficients: [18.83816048 64.55968825]


In [54]:
print("Intercept:", regr.intercept_)

Intercept: 1.4512607561654027


#### Prediction

In [55]:
X_test = np.array([[1, 1], [2, 2], [1, 2], [2, 1]])
regr.predict(X_test)

array([ 84.84910948, 168.2469582 , 149.40879773, 103.68726995])

Prediction new values from Elastic Net model is the same like for normal linear regression model. It's mean that all what we have to do is take our coefficients and multiplicate them by proper feature. 

$Example$

In [65]:
def Elastic_Net_predict(X_test):
    b0 = regr.intercept_
    b1 = regr.coef_[0]
    b2 = regr.coef_[1]
    X1 = X_test[:, 0]
    X2 = X_test[:, 1] 
    return b0 + b1*X1 + b2*X2 

In [66]:
Elastic_Net_predict(X_test)

array([ 84.84910948, 168.2469582 , 149.40879773, 103.68726995])

#### Modelling: Elastic Net with Cross Validation

In [69]:
regrcv = ElasticNetCV(cv = 5, random_state=0)
regrcv.fit(X, y)

ElasticNetCV(alphas=None, copy_X=True, cv=5, eps=0.001, fit_intercept=True,
             l1_ratio=0.5, max_iter=1000, n_alphas=100, n_jobs=None,
             normalize=False, positive=False, precompute='auto', random_state=0,
             selection='cyclic', tol=0.0001, verbose=0)

In [72]:
print("Intercept:", regrcv.intercept_)

Intercept: 0.3988829654276791


In [73]:
print("Regression coefficients:", regrcv.coef_)

Regression coefficients: [26.36379145 87.65898443]


In [74]:
print("Best alpha:", regrcv.alpha_)

Best alpha: 0.1994727942696716


#### Simple Example

In [130]:
from sklearn.linear_model import LinearRegression 

In [131]:
# Features
x_1 = np.arange(1, 11)
x_2 = np.arange(2, 22, 2)
X = np.array([x_1, x_2]).transpose()

# Target
y = np.arange(3, 33, 3)

Elastic Net model it is a connection of Ridge and Lasso regularization. Both methods used for shrinkage regression parameters to avoid overfitting and reduce variance from our model. Ridge method used L2 norm 

In [140]:
# Elastic Net 
model_en = ElasticNet(random_state=0, alpha = 0.5, l1_ratio=0.5)
model_en.fit(X, y)

ElasticNet(alpha=0.5, copy_X=True, fit_intercept=True, l1_ratio=0.5,
           max_iter=1000, normalize=False, positive=False, precompute=False,
           random_state=0, selection='cyclic', tol=0.0001, warm_start=False)

In [135]:
print("Coefficients:", model_en.coef_)
print("Intercept:", model_en.intercept_)

Coefficients: [0.19635807 1.38376216]
Intercept: 0.19864684688648282


In [136]:
model_en.predict(X)

array([ 3.16252924,  6.12641163,  9.09029402, 12.05417641, 15.0180588 ,
       17.9819412 , 20.94582359, 23.90970598, 26.87358837, 29.83747076])

In [137]:
print(X[:, 0] + X[:, 1])
print(y)

[ 3  6  9 12 15 18 21 24 27 30]
[ 3  6  9 12 15 18 21 24 27 30]


In [141]:
# Elastic Net CV
model_encv = ElasticNetCV(random_state = 0)
model_encv.fit(X, y)

ElasticNetCV(alphas=None, copy_X=True, cv=None, eps=0.001, fit_intercept=True,
             l1_ratio=0.5, max_iter=1000, n_alphas=100, n_jobs=None,
             normalize=False, positive=False, precompute='auto', random_state=0,
             selection='cyclic', tol=0.0001, verbose=0)

In [142]:
print("Coefficents:", model_encv.coef_)
print("Intercept:", model_encv.intercept_)
print("Best alpha", model_encv.alpha_)

Coefficents: [0.21691155 1.38796228]
Intercept: 0.03940137766541696
Best alpha 0.09899999999999999


In [143]:
model_encv.predict(X)

array([ 3.03223749,  6.0250736 ,  9.01790972, 12.01074583, 15.00358194,
       17.99641806, 20.98925417, 23.98209028, 26.9749264 , 29.96776251])

In [134]:
# Linear Regression
model_lm = LinearRegression(normalize=True)
model_lm.fit(X, y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=True)

In [138]:
model_lm.predict(X)

array([ 3.,  6.,  9., 12., 15., 18., 21., 24., 27., 30.])